### ISSUE TITLE
Update to studio release 14

### ISSUE THREAD

**Issue by literadix** [PaoloRotolo/android-studio#15]
Hello my friends !

Is there a way that you create a new package update providing release 14 of android studio? This would be great. The version is now stable. Probably you could publish a short instruction how to update the dep package, so others could help you.

Thank you very much,

Maciej

**Comment by PaoloRotolo** [comment]
Fixed in latest commit. Launchpad will upload the new builds on PPA very soon.
BTW, the code is heavily commented. You just have to update the link in ```debian/preinst/``` :)
