### ISSUE TITLE
Unmet dependencies

### ISSUE THREAD

**Issue by p-brane** [PaoloRotolo/android-studio#5]
I get the following error message from the install.

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 android-studio : Depends: lib32ncurses5 but it is not installable
                  Depends: libc6-i386 but it is not installable
                  Depends: lib32stdc++6 but it is not installable
                  Depends: lib32gcc1 but it is not installable
                  Depends: lib32z1 but it is not installable
                  Depends: lib32z1-dev but it is not installable
E: Unable to correct problems, you have held broken packages.

These dependencies don have an installation candidate or is not avaiable.

**Comment by PaoloRotolo** [comment]
Hi p-brane,
thanks for your report!

Can you please tell me which release of Ubuntu are you using?

**Comment by p-brane** [comment]
Hi Paolo,
      I'm using
      Distributor ID:    Ubuntu
        Description:    Ubuntu 14.04.2 LTS
        Release:    14.04
        Codename:    trusty
      
      Sincerely,
Jay Morreale
p-brane LLC


      On 2/23/2015 4:10 PM, Paolo Rotolo wrote:
    
    
      Hi p-brane,
        thanks for your report!
      Can you please tell me which release of Ubuntu are you using?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by PaoloRotolo** [comment]
Thank you again! I'll let you know.

**Comment by PaoloRotolo** [comment]
I think it's an issue with your PC...
*lib32ncurses5* is actually installable on Ubuntu 14.04: http://packages.ubuntu.com/search?keywords=lib32ncurses5

**Comment by p-brane** [comment]
Hi Paolo,
The link that you send indicates that the package is for a amd64 architecture. My Linux PC is a 3GHz Intel Pentium 4 so perhaps those file are not the correct packages for this machine.

**Comment by aimanbaharum** [comment]
Hi, I have the exact same problem. Is this build only for 64 bit machine? I'm using a 32-bit Ubuntu 14.04.2.

**Comment by hoodaajay99** [comment]
Same problem encountered for 12.04.5 on 32 bit machine
The following packages have unmet dependencies:
 android-studio : Depends: lib32ncurses5 but it is not installable
                  Depends: libc6-i386 but it is not installable
                  Depends: lib32stdc++6 but it is not installable
                  Depends: lib32gcc1 but it is not installable
                  Depends: lib32z1 but it is not installable
                  Depends: lib32z1-dev but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by ggiacomo** [comment]
:+1:  same issue

**Comment by PaoloRotolo** [comment]
Thanks for your reports! Can you please tell me if you're able to install `libncurses5-dev:i386` on Ubuntu i386?

Just try `sudo apt-get install libncurses5-dev:i386`

**Comment by unusualinsights** [comment]
Hi, I also have the same problem.  I'm running Ubuntu precise 12.04.5 LTS on a 32-bit i386 machine.  I tried your suggestion, "sudo apt-get install libncurses5-dev:i386" and it appears to have installed successfully.  Does that suggest there may be a workaround for installing Android Studio on 32-bit Ubuntu machines?

**Comment by unusualinsights** [comment]
The main workaround that's working for me (so far) is just to download Android Studio directly from the main website and install it:
1) Go to http://developer.android.com/sdk/index.html#Other
2) Scroll all the way to the bottom.
3) Download the last file, android-studio-ide-135.1740770-linux.zip, preferably to somewhere within your own home directory like ~/Downloads or ~/software.
4) Open a terminal and cd to where you downloaded the .zip file.
5) unzip android-studio-ide-135.1740770-linux.zip
6) If you want, move the resulting android-studio folder where you want the Android Studio software package's files to be located.  It may be safer to keep the android-studio folder somewhere within your home directory, such as within a folder like ~/software, so you don't need root privileges to perform various operations later.
7) In a terminal window, cd to this android-studio folder.
8) Run ./studio.sh, which will launch the wizard for installing Android Studio.

Source: http://askubuntu.com/a/585476
Note: I got some "ERROR - pplication.impl.LaterInvocator" errors when running ./studio.sh, which don't seem to have prevented me from running Android Studio.  According to http://stackoverflow.com/questions/16662391/android-studio-error-startup-in-ubuntu, using "sudo -i ./studio.sh" might eliminate these errors, but I haven't verified this myself.

Of course, I'm sure many people would still prefer to have Android Studio via apt-get for 32-bit machines!

**Comment by mayankcool786** [comment]
@unusualinsights  Actually I hae followed the same ways , I have downloaded Android Studio from google website but its asking me to give the path for the sdk. But after extracting Android Studio zip .. I am not able to see the sdk folder in it ..Could you please help me out ?
Thanks in advance !!

**Comment by PaoloRotolo** [comment]
Ok guys, I'm going to upload a new release tonight. It should fix the depends bug on i386.
Stay tuned :)

**Comment by unusualinsights** [comment]
@mayankcool786 At what point during installing or running is it asking you for the SDK path?  I ran into an issue like this when trying to run a project with an emulator, like the problem described <a href="http://stackoverflow.com/q/28864785">here</a>.  The solution was to ensure the ARM EABI v7a System Image was for the Android version specified for that emulator, as described <a href="http://stackoverflow.com/a/10101698">here.</a>

**Comment by PaoloRotolo** [comment]
I just pushed a new release on PPA. **It should fix the dependences issue on i386** and update Android Studio to 1.2 Beta 3.

Can you please confirm? I haven't i386 machines to test it.

**Comment by PaoloRotolo** [comment]
Hi again! I uploaded another release (4.8.2).
It should work well on 32 bit devices now. **Can you please confirm?**

**Comment by unusualinsights** [comment]
Yes, I can confirm that this new release (4.8.2) works!  Thanks a lot!

For those who may have followed my instructions above, you can follow the <a href="https://paolorotolo.github.io/android-studio/">three steps on the main page</a>.  Then, launch this new version of Android Studio (on my system, which is Kubuntu (KDE+Ubuntu) 12.04, this program appeared under my KDE application launcher (a.k.a. "start menu") under Applications -> Development folder).  A window will pop up asking if you want to import a configuration from a previous installation of Android Studio - it found the one I had installed following my instructions above, so I let it import that configuration, and everything appears to be working so far.

**Comment by PaoloRotolo** [comment]
Awesome. Thanks for the support guys :)
